Fixed handshake bug that caused all inbound connections to fail with: ``"AttributeError: 'Session' object has no attribute 'address'"``
